name: Deploy Solution to UAT

on:
  push:
    branches:
      - main

jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:
      # 1) Get the code from your repo (src/MySolution)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install Power Platform CLI on the runner
      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1
        with:
          pac-version-override: 1.30.4
          add-tools-to-path: true

      # 3) Pack solution from src/MySolution into a zip
      - name: Pack solution
        run: |
          mkdir out
          pac solution pack --folder ./src/MySolution --zipfile ./out/AP637_Managed.zip

      # 4) Authenticate to UAT using your Service Principal
      - name: Authenticate with SP (UAT)
        env:
          TENANT: ${{ secrets.AZURE_TENANT_ID }}
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ENV_URL: ${{ secrets.PP_UAT_URL }}
        run: |
          pac auth create --applicationId $CLIENT_ID --clientSecret $CLIENT_SECRET --tenant $TENANT --environment $PP_UAT_URL --name sp-uat

      # 5) Import the solution into UAT
      - name: Import solution to UAT
        run: |
          pac solution import --path ./out/AP637_Managed.zip --overwrite true
