name: Deploy AMLGit Solution to UAT

on:
  push:
    branches:
      - main

jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1
        with:
          pac-version-override: 1.30.4
          add-tools-to-path: true

      - name: Pack AMLGit Solution
        run: |
          mkdir out
          pac solution pack --folder ./src/AMLGit --zipfile ./out/AMLGit_Managed.zip

      - name: Authenticate to UAT
        env:
          TENANT: ${{ secrets.AZURE_TENANT_ID }}
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ENV_URL: ${{ secrets.PP_DEV_URL }}
        run: |
          pac auth create --applicationId $CLIENT_ID --clientSecret $CLIENT_SECRET --tenant $TENANT --environment $ENV_URL --name sp-uat

      - name: Import Solution into Dev
        run: |
          pac solution import --path ./out/AMLGit_Managed.zip --force-overwrite

